<a href="https://colab.research.google.com/github/Fenriro37/d2l/blob/main/dataManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf 
X = tf.reshape(tf.range(24, dtype=tf.float32), (3, 4, 2))
Y = tf.constant([[[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], [[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]])
print('X', X)
print('Y', Y)
"""
from last dimension to first check if the two number are compatible:
equal or one of them is equal to 1
"""
print(tf.concat([X,Y], axis=0))
print(tf.concat([X,Y] , axis=1))
print(X == Y)
#print(X < Y)
#print(X > Y)
#print(tf.reduce_sum(X))


X tf.Tensor(
[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]
  [ 6.  7.]]

 [[ 8.  9.]
  [10. 11.]
  [12. 13.]
  [14. 15.]]

 [[16. 17.]
  [18. 19.]
  [20. 21.]
  [22. 23.]]], shape=(3, 4, 2), dtype=float32)
Y tf.Tensor(
[[[2. 1. 4. 3.]
  [1. 2. 3. 4.]
  [4. 3. 2. 1.]]

 [[2. 1. 4. 3.]
  [1. 2. 3. 4.]
  [4. 3. 2. 1.]]], shape=(2, 3, 4), dtype=float32)


InvalidArgumentError: ignored

In [ ]:
a = tf.reshape(tf.range(3), (3,1))
b = tf.reshape(tf.range(2), (1,2))
print(a)
print(b)
print(a+b)

tf.Tensor(
[[0]
 [1]
 [2]], shape=(3, 1), dtype=int32)
tf.Tensor([[0 1]], shape=(1, 2), dtype=int32)
tf.Tensor(
[[0 1]
 [1 2]
 [2 3]], shape=(3, 2), dtype=int32)


In [ ]:
X_var = tf.Variable(X)
X_var[1, 2].assign(9)
print(X_var)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>


In [ ]:
X_var = tf.Variable(X)
X_var[0:2, :].assign(tf.ones(X_var[0:2,:].shape, dtype = tf.float32) * 12)
print(X_var)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)>


In [ ]:
"""
before = id(Y)
print(before)
Y = Y + X
print(id(Y))
id(Y) == before
"""

140594015464144
140594015463760


False

In [ ]:
Z = tf.Variable(tf.zeros_like(Y))
print('id(Z):', id(Z))
Z.assign(X + Y)
print('id(Z):', id(Z))

id(Z): 140594024630096
id(Z): 140594024630096


In [ ]:
@tf.function
def computation(X, Y):
    Z = tf.zeros_like(Y)  # This unused value will be pruned out
    A = X + Y  # Allocations will be re-used when no longer needed
    B = A + Y
    C = B + Y
    return C + Y

computation(X, Y)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[  8.,  17.,  42.,  51.],
       [ 56.,  73.,  90., 107.],
       [120., 129., 138., 147.]], dtype=float32)>

In [ ]:
A = X.numpy()
B = tf.constant(A)
print(type(A), type(B))

<class 'numpy.ndarray'> <class 'tensorflow.python.framework.ops.EagerTensor'>
