<a href="https://colab.research.google.com/github/Fenriro37/d2l/blob/main/dataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
print(data_file)
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # Column names
    f.write('2,Pave,127500\n')  # Each row represents a data example
    f.write('3,NA,106000\n')
    f.write('NA,NA,178100\n')
    f.write('1,NA,140000\n')

../data/house_tiny.csv


In [42]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       2.0  Pave  127500
1       3.0   NaN  106000
2       NaN   NaN  178100
3       1.0   NaN  140000


In [48]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2] #iloc = integerLocation. Split the table using pandas method
inputs = inputs.fillna(inputs.mean()) #NaN become equal to the mean in that specific column
print('inputs \n', inputs)
print('outputs \n', outputs)

inputs 
    NumRooms Alley
0       2.0  Pave
1       3.0   NaN
2       2.0   NaN
3       1.0   NaN
outputs 
 0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  


In [50]:
inputs = pd.get_dummies(inputs, dummy_na=True) #in this case we only have two values (Pave, NaN)  for Alley so get_dummies() creates two columns from it: 1 where Alley is Pave/NaN and 0 otherwise 
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       2.0           1          0
1       3.0           0          1
2       2.0           0          1
3       1.0           0          1


In [45]:
import tensorflow as tf

X, y = tf.constant(inputs.values), tf.constant(outputs.values)
print(X)
print(y)

tf.Tensor(
[[2. 1. 0.]
 [3. 0. 1.]
 [2. 0. 1.]
 [1. 0. 1.]], shape=(4, 3), dtype=float64)
tf.Tensor([127500 106000 178100 140000], shape=(4,), dtype=int64)


In [49]:
def get_max_col_name(data):
  print(type(data))
  print(data)
  max = data.isnull().sum().max()  #isnull() converts the dataframe to boolean where NaN becomes true. sum() iterates for every column and count how many values are true. max() returns the maximum value
  """
  print(type(data.isnull()))
  print('null \n',data.isnull())
  nullColums = data.isnull().sum()
  print(type(nullColums))
  print('sum \n',nullColums)
  print('max \n',data.isnull().sum().max())
  """
  for i in range(len(data.columns)):
    if data.iloc[:,i].isnull().sum() == max:
      """
      print('iloc \n',data.iloc[:,i].name)
      print('iloc \n',data.iloc[:,i])
      """
      return data.iloc[:,i].name
      
data_dropna = data.drop(columns=[get_max_col_name(data)], axis=1)  #drop() lets you remove parts of the dataframe, in this case the column with more NaN
print(data_dropna)

<class 'pandas.core.frame.DataFrame'>
   NumRooms Alley   Price
0       2.0  Pave  127500
1       3.0   NaN  106000
2       NaN   NaN  178100
3       1.0   NaN  140000
   NumRooms   Price
0       2.0  127500
1       3.0  106000
2       NaN  178100
3       1.0  140000
