<a href="https://colab.research.google.com/github/Fenriro37/d2l/blob/main/Preliminarie/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Scalars

In [1]:
import tensorflow as tf

x = tf.constant(3.0)
y = tf.constant(2.0)
print(x,y)

tf.Tensor(3.0, shape=(), dtype=float32) tf.Tensor(2.0, shape=(), dtype=float32)


#Vectors

In [2]:
x = tf.range(4)
print(x)
print(x[3])
print(len(x))
print(x.shape)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
4
(4,)


#Matrices

In [21]:
A = tf.reshape(tf.range(20), (5,4))
tf.cast(A, tf.float32)
print(A)
print(A[3][3])
AT = tf.transpose(A)
print(AT)

B = tf.constant([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(B)
print(B == tf.transpose(B)) #true because B is a symmetric matrix

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]], shape=(5, 4), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)
tf.Tensor(
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]], shape=(4, 5), dtype=int32)
tf.Tensor(
[[1 2 3]
 [2 0 4]
 [3 4 5]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]], shape=(3, 3), dtype=bool)


#Tensors

In [22]:
X = tf.reshape(tf.range(24),(2, 3, 4))
print(X)
print(tf.reduce_sum(X)) #sum of every elements 
A_sum_axis0 = tf.reduce_sum(A, axis=0)
print(A_sum_axis0, A_sum_axis0.shape)
sum_A = tf.reduce_sum(A, axis=1, keepdims=True)
print(sum_A)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(276, shape=(), dtype=int32)
tf.Tensor([40 45 50 55], shape=(4,), dtype=int32) (4,)
tf.Tensor(
[[ 6]
 [22]
 [38]
 [54]
 [70]], shape=(5, 1), dtype=int32)


#Dot Products
Given two vectors their dot product is a sum over the products of the elements at the same position

In [27]:
x = tf.range(4, dtype=tf.int32)
y = tf.ones(4, dtype=tf.int32)
tf.tensordot(x, y, axes=1)
tf.reduce_sum(x * y) 

<tf.Tensor: shape=(), dtype=int32, numpy=6>

#Matrix-Vector Products

In [28]:
tf.linalg.matvec(A, x)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 14,  38,  62,  86, 110], dtype=int32)>

# Matrix-Matrix Multiplication

In [30]:
B = tf.ones((4, 3), tf.int32)
tf.matmul(A, B)

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[ 6,  6,  6],
       [22, 22, 22],
       [38, 38, 38],
       [54, 54, 54],
       [70, 70, 70]], dtype=int32)>

# Norms
The norm of a vector tells us how big a vector is

In [31]:
u = tf.constant([3.0, -4.0])
tf.norm(u) #norm2
tf.reduce_sum(tf.abs(u)) #norm1

tf.Tensor(5.0, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=7.0>